Baseline:
  LUNARLANDER:
    gym_id: mo-LunarLanderContinuous-v2
    num_envs: 16
    total_timesteps: 200000
  HOPPER:
    gym_id: mo-Hopper-v4
    num_envs: 16
    total_timesteps: 500000
  PENDULUM:
    gym_id: mo-Pendulum-v1
    num_envs: 16
    total_timesteps: 100000
  HUMANOID:
    gym_id: mo-Humanoid-v4
    num_envs: 16
    total_timesteps: 500000
  VSS:
    gym_id: mo-VSS-v0
    num_envs: 20
    total_timesteps: 500000
    sigma_decay: 150
    sigma_min: 0.15
    learning_starts: 5000
    tau: 0.999
    policy_frequency: 1
    policy_lr: 0.0001
    q_lr: 0.0001
    batch_size: 256
    n_hidden: 4
    gamma: 0.95
    update_frequency: 1

Dylam:
  LUNARLANDER:
    gym_id: mo-LunarLanderContinuous-v2
    num_envs: 16
    total_timesteps: 200000
    stratified: True
    dylam: True
    num_rewards: 4
    r_max: [1000, -0, 0, 1]
    r_min: [-1000, -1000, -1000, -1]
    dylam_rb: 100
  HOPPER:
    gym_id: mo-Hopper-v4
    num_envs: 16
    total_timesteps: 500000
    stratified: True
    dylam: True
    num_rewards: 4
    r_max: [1000, 1000, -100, 1000]
    r_min: [0, -200, -250, 0]
    dylam_rb: 100
    dylam_tau: 0.9999
  PENDULUM:
    gym_id: mo-Pendulum-v1
    num_envs: 16
    total_timesteps: 100000
    stratified: True
    dylam: True
    num_rewards: 3
    r_max: [0, 0, 0]
    r_min: [-100, -100, -100]
  HUMANOID:
    gym_id: mo-Humanoid-v4
    num_envs: 16
    total_timesteps: 500000
    stratified: True
    dylam: True
    num_rewards: 3
    r_max: [1000, 0, 1000]
    r_min: [0, -1000, 0]
    dylam_rb: 100
    dylam_tau: 0.9999
  VSS:
    gym_id: mo-VSS-v0
    num_envs: 20
    total_timesteps: 500000
    sigma_decay: 150
    sigma_min: 0.15
    learning_starts: 5000
    tau: 0.999
    policy_frequency: 1
    policy_lr: 0.0001
    q_lr: 0.0001
    batch_size: 256
    n_hidden: 4
    gamma: 0.95
    update_frequency: 1
    stratified: True
    dylam: True
    num_rewards: 4
    r_max: [150, 40, -400, 1]
    r_min: [0, 0, -600, 0]
    dylam_rb: 100
    dylam_tau: 0.9999