"""Beyond PDF build entry point.

Runs the Embed generators, then assembles beyond_pdf/submission_folder into
beyond_pdf/tmlr_do_not_modify (the author kit) and starts the kit's local
Docker/Jekyll render, by invoking the kit's own compile_submission.py --
which already implements that merge-and-serve sequence. compile_submission.py
is left untouched so the vendored kit stays a faithful, diffable copy.

Step order:
  1. build_scrubber() -- runs beyond_pdf/export.py (the lambda-simplex
     scrubber Embed generator from issue #38, wired into this build by
     issue #43) against real ChickenBanana/Dylam checkpoints and writes the
     Embed HTML under submission_folder/assets/html/submission/, where
     compile_submission.py's own copy step already looks (see its
     merge_files()). Those checkpoints -- scripts/train_q_learning.py
     --checkpoint-interval snapshots -- are NOT committed to this
     repository (see export.py's module docstring and issue #39's
     "Checkpoint availability" note), so this step is expected to be
     unavailable on a fresh clone. It fails gracefully: a diagnostic on
     stderr and a skip, not a fabricated artifact and not a crash that
     blocks the rest of the build.
  2. build_mechanism_explainer() -- runs beyond_pdf/mechanism_export.py (the
     mechanism explainer Embed generator from issue #47) against the same
     checkpoints as build_scrubber(), and is subject to the same
     "Checkpoint availability" caveat and the same graceful skip.
  3. build_ablation_curves() -- runs beyond_pdf/ablation_export.py (the
     ablation explorer Embed generator from issue #48) against the ablation
     scope's committed Tidy CSVs. Unlike steps 1-2, this needs no external
     checkpoints, so it runs unconditionally, including on a fresh clone.
  4. build_static_figures() / build_morl_figures() -- regenerate the Results
     section's (issue #46) SVG/PNG figures via the SVG mode issue #41 added
     to their owning scope Generators, and copy the ones submission.md
     references into submission_folder/assets/img/submission under stable
     names. Reads only the committed Tidy CSVs under result_analysis/*/data/,
     so -- like build_ablation_curves() and unlike build_scrubber() -- these
     steps run on a fresh clone.
  5. assemble_and_serve() -- the kit's existing merge-and-serve sequence.

submission.md's data tables (issue #46/#48) are not regenerated by this
step: the kit's compile_submission.py only copies submission_folder's
assets/{bibliography,css,html,img,gif} directories into the author kit, with
no include mechanism for injecting a generated fragment into the authored
markdown. Their HTML is instead produced once by running the owning scope's
`table.py --format html` and pasted into submission.md at the marked
<table> blocks -- the same "port once, re-run when the source changes"
model ADR-0002 already accepts for the ported prose.

This is the one build entry point; new steps land here rather than in
parallel scripts.
"""

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

BEYOND_PDF_DIR = Path(__file__).resolve().parent
REPO_ROOT = BEYOND_PDF_DIR.parent
EXPORT_SCRIPT = BEYOND_PDF_DIR / "export.py"
ABLATION_EXPORT_SCRIPT = BEYOND_PDF_DIR / "ablation_export.py"
ENV_EXPORT_SCRIPT = BEYOND_PDF_DIR / "env_export.py"
PARETO_EXPORT_SCRIPT = BEYOND_PDF_DIR / "pareto_export.py"
MECHANISM_EXPORT_SCRIPT = BEYOND_PDF_DIR / "mechanism_export.py"
RESULT_ANALYSIS_DIR = REPO_ROOT / "result_analysis"
CURRICULUM_DATA = RESULT_ANALYSIS_DIR / "curriculum" / "data"
ACTUAL_RETURNS = BEYOND_PDF_DIR / "data" / "chickenbanana_actual_returns.csv"
SUBMISSION_HTML_DIR = (
    BEYOND_PDF_DIR / "submission_folder" / "assets" / "html" / "submission"
)
SUBMISSION_IMG_DIR = (
    BEYOND_PDF_DIR / "submission_folder" / "assets" / "img" / "submission"
)
SCRUBBER_OUT = SUBMISSION_HTML_DIR / "lambda_simplex_scrubber.html"
ABLATION_CURVES_OUT = SUBMISSION_HTML_DIR / "ablation_curves.html"
ENV_CURVES_OUT = SUBMISSION_HTML_DIR / "env_curves.html"
PARETO_EXPLORER_OUT = SUBMISSION_HTML_DIR / "pareto_explorer.html"
MECHANISM_EXPLAINER_OUT = SUBMISSION_HTML_DIR / "mechanism_explainer.html"

# The worked window the mechanism explainer (issue #47) shows: episode 200 of
# the same seed the scrubber Embed uses (SCRUBBER_SEED), inside the
# "weight concentration" phase the curriculum subsection's prose names
# (episodes 0-250), where Chicken's weight is visibly rising against the
# still-saturating Objective/Banana components -- the most legible single
# window to walk through the update on.
MECHANISM_WINDOW_END = 200

# scope directories under result_analysis/ whose figure.py this step drives
# with --format svg (issue #41).
FIGURE_SCOPES = ["trad", "curriculum", "robustness"]

# scratch-relative output path (as each scope's figure.py --format svg
# writes it, per its own OUT_DIR/out_rel constants) -> stable filename under
# submission_folder/assets/img/submission, referenced by submission.md's
# <img> tags. The per-environment curriculum/per-component figures the map
# once carried are gone with #49 (superseded by the env_curves Embed), and
# the Pareto front scatters with #50 (superseded by the Pareto explorer);
# what remains is fig:res/all's three panels, the robustness curves, and
# the HalfCheetah weight-space scatter (the weight simplex has no hover
# mapping in the explorer's front view, so the static panel stays).
FIGURE_MAP = {
    "images/results/tradicional/chicken_banana/reward-total.svg": "trad_reward_total.svg",
    "images/results/tradicional/halfcheetah/HalfCheetah-v4.svg": "trad_halfcheetah_position.svg",
    "images/results/tradicional/vss/VSS-v0.svg": "trad_vss_goal.svg",
    "images/results/robustness_curves.svg": "robustness_curves.svg",
}

# submission_folder/assets/img/submission/chicken_banana_env.png is a raw
# screenshot asset from the manuscript repository (DyLam-TMLR), not a
# Generator artifact -- "Environment screenshots stay raster" (issue #39).
# Committed directly; no build step regenerates it.

# The published seed the scrubber Embed is built from: the lower of the two
# middle published seeds, ranked by mean summed per-Component return over the
# final 10% of episodes (export.py's DEFAULT_SEED_CRITERION). Matches the
# #38 artifact this build step replaces (see that commit's message).
SCRUBBER_SEED = 1764531329
SCRUBBER_LATTICE_STEP = 20

# Not committed -- see build_scrubber()'s docstring. Reproduce by training
# this seed with scripts/train_q_learning.py --setup Dylam --env
# CHICKENBANANA --seed 1764531329 --checkpoint-interval 10, then point
# --snapshots-dir at the run's models/.../snapshots directory.
DEFAULT_SNAPSHOTS_DIR = (
    REPO_ROOT / "scripts" / "models" / "chickenbanana_dylam_snapshots"
)


def build_scrubber(snapshots_dir=DEFAULT_SNAPSHOTS_DIR):
    """Build the lambda-simplex scrubber Embed via beyond_pdf/export.py and
    write it into the submission folder's assets/html/submission/ directory,
    where compile_submission.py's merge step already picks up per-page HTML
    subdirectories. Returns True if the artifact was (re)built, False if the
    step was skipped because no checkpoints were found."""
    snapshots_dir = Path(snapshots_dir)
    if not snapshots_dir.is_dir():
        print(
            "beyond_pdf build: skipping the lambda-simplex scrubber Embed -- "
            f"no snapshots directory at {snapshots_dir}. This step needs real "
            "ChickenBanana/Dylam checkpoints from scripts/train_q_learning.py's "
            "--checkpoint-interval flag, which are not committed to this "
            "repository (see beyond_pdf/export.py's module docstring and "
            'issue #39\'s "Checkpoint availability" note). Train seed '
            f"{SCRUBBER_SEED} with --checkpoint-interval 10, then re-run this "
            "build with --snapshots-dir pointing at the resulting snapshots/ "
            "directory. The existing artifact in the submission folder (if "
            "any) is left as-is.",
            file=sys.stderr,
        )
        return False

    SUBMISSION_HTML_DIR.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable,
        str(EXPORT_SCRIPT),
        "--snapshots",
        str(snapshots_dir),
        "--out",
        str(SCRUBBER_OUT),
        "--curriculum-data",
        str(CURRICULUM_DATA),
        "--seed",
        str(SCRUBBER_SEED),
        "--lattice-step",
        str(SCRUBBER_LATTICE_STEP),
        "--actual-returns",
        str(ACTUAL_RETURNS),
    ]
    subprocess.run(cmd, check=True)
    return True


def build_mechanism_explainer(snapshots_dir=DEFAULT_SNAPSHOTS_DIR):
    """Build the mechanism explainer Embed (issue #47) via
    beyond_pdf/mechanism_export.py and write it into the submission folder's
    assets/html/submission/ directory. Needs the same ChickenBanana/Dylam
    checkpoint snapshots as build_scrubber() -- see that function's
    docstring -- so it fails gracefully the same way when they are absent.
    Returns True if the artifact was (re)built, False if skipped."""
    snapshots_dir = Path(snapshots_dir)
    if not snapshots_dir.is_dir():
        print(
            "beyond_pdf build: skipping the mechanism explainer Embed -- "
            f"no snapshots directory at {snapshots_dir}. Same checkpoint "
            "requirement as the lambda-simplex scrubber; see build_scrubber's "
            "diagnostic above for how to reproduce them.",
            file=sys.stderr,
        )
        return False

    SUBMISSION_HTML_DIR.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable,
        str(MECHANISM_EXPORT_SCRIPT),
        "--snapshots",
        str(snapshots_dir),
        "--out",
        str(MECHANISM_EXPLAINER_OUT),
        "--window-end",
        str(MECHANISM_WINDOW_END),
    ]
    subprocess.run(cmd, check=True)
    return True


def build_static_figures(scratch_dir):
    """Regenerate the Results section's (issue #46) static SVG figures by
    running each scope's figure.py --format svg into `scratch_dir`, then
    copying the ones FIGURE_MAP names into submission_folder/assets/img/
    submission under their stable filenames. Reads only the committed Tidy
    CSVs under result_analysis/*/data/, so -- unlike build_scrubber() --
    this runs on a fresh clone with no external inputs."""
    scratch_dir = Path(scratch_dir)
    for scope in FIGURE_SCOPES:
        subprocess.run(
            [
                sys.executable,
                str(RESULT_ANALYSIS_DIR / scope / "figure.py"),
                "--out-path",
                str(scratch_dir),
                "--format",
                "svg",
            ],
            check=True,
        )
    SUBMISSION_IMG_DIR.mkdir(parents=True, exist_ok=True)
    for rel, name in FIGURE_MAP.items():
        shutil.copyfile(scratch_dir / rel, SUBMISSION_IMG_DIR / name)
        print(f"wrote {SUBMISSION_IMG_DIR / name}", file=sys.stderr)


def build_morl_figures(scratch_dir):
    """Regenerate the HalfCheetah weight-space scatter the submission still
    carries (the Pareto front scatters themselves were superseded by the
    Pareto explorer Embed, issue #50). figure.py's weight draw is reused
    untouched -- only the output sink changes."""
    scratch_dir = Path(scratch_dir)
    morl_dir = RESULT_ANALYSIS_DIR / "morl"
    sys.path.insert(0, str(RESULT_ANALYSIS_DIR))
    sys.path.insert(0, str(morl_dir))
    import figure as morl_figure  # noqa: E402

    def render_png(fig, out, fmt="pdf", **kwargs):
        kwargs.pop("dpi", None)
        png_out = out.with_suffix(".png")
        # style.savefig mkdirs the output path; this replacement sink must
        # too -- the scratch tree does not exist beforehand.
        png_out.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(png_out, dpi=150, **kwargs)
        print(f"wrote {png_out}", file=sys.stderr)
        return [png_out]

    morl_figure.style.savefig = render_png
    morl_figure.draw_halfcheetah_weights(scratch_dir)

    SUBMISSION_IMG_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(
        scratch_dir / "images/results/pareto/halfcheetah_weights_comparison.png",
        SUBMISSION_IMG_DIR / "morl_hc_weights.png",
    )


def build_ablation_curves():
    """Build the ablation explorer Embed (issue #48) via
    beyond_pdf/ablation_export.py and write it into the submission folder's
    assets/html/submission/ directory. Reads only the committed Tidy CSVs
    under result_analysis/ablation/data/, so -- unlike build_scrubber() --
    this runs unconditionally on a fresh clone."""
    SUBMISSION_HTML_DIR.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            sys.executable,
            str(ABLATION_EXPORT_SCRIPT),
            "--out",
            str(ABLATION_CURVES_OUT),
        ],
        check=True,
    )


def build_env_curves():
    """Build the per-environment curve explorer Embed (issue #49) via
    beyond_pdf/env_export.py -- the shared curves template's second data
    blob. Reads only the committed Tidy CSVs under
    result_analysis/{trad,curriculum}/data/, so it runs unconditionally on
    a fresh clone."""
    SUBMISSION_HTML_DIR.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [sys.executable, str(ENV_EXPORT_SCRIPT), "--out", str(ENV_CURVES_OUT)],
        check=True,
    )


def build_pareto_explorer():
    """Build the Pareto explorer Embed (issue #50) via
    beyond_pdf/pareto_export.py. Reads only the committed Tidy CSVs under
    result_analysis/morl/data/, so it runs unconditionally on a fresh
    clone."""
    SUBMISSION_HTML_DIR.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [sys.executable, str(PARETO_EXPORT_SCRIPT), "--out", str(PARETO_EXPLORER_OUT)],
        check=True,
    )


def assemble_and_serve():
    subprocess.run(
        [sys.executable, "compile_submission.py"],
        cwd=BEYOND_PDF_DIR,
        check=True,
    )


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--snapshots-dir",
        type=Path,
        default=DEFAULT_SNAPSHOTS_DIR,
        help="ChickenBanana/Dylam checkpoint snapshots for the "
        "scrubber Embed (not committed to this repository)",
    )
    ap.add_argument(
        "--skip-scrubber",
        action="store_true",
        help="skip the scrubber Embed generation step",
    )
    ap.add_argument(
        "--skip-mechanism",
        action="store_true",
        help="skip the mechanism explainer Embed generation step",
    )
    ap.add_argument(
        "--skip-ablation",
        action="store_true",
        help="skip the ablation explorer Embed generation step",
    )
    ap.add_argument(
        "--skip-env-curves",
        action="store_true",
        help="skip the per-environment curve explorer Embed generation step",
    )
    ap.add_argument(
        "--skip-pareto",
        action="store_true",
        help="skip the Pareto explorer Embed generation step",
    )
    ap.add_argument(
        "--skip-figures",
        action="store_true",
        help="skip regenerating the Results section's static SVG figures",
    )
    ap.add_argument(
        "--figures-scratch-dir",
        type=Path,
        default=None,
        help="scratch directory for intermediate figure.py output "
        "(default: a temporary directory, cleaned up after the build)",
    )
    ap.add_argument(
        "--skip-serve",
        action="store_true",
        help="run the Embed generation steps but skip the kit's "
        "assemble + Docker/Jekyll serve step",
    )
    args = ap.parse_args()

    if not args.skip_scrubber:
        build_scrubber(args.snapshots_dir)

    if not args.skip_mechanism:
        build_mechanism_explainer(args.snapshots_dir)

    if not args.skip_ablation:
        build_ablation_curves()

    if not args.skip_env_curves:
        build_env_curves()

    if not args.skip_pareto:
        build_pareto_explorer()

    if not args.skip_figures:
        if args.figures_scratch_dir is not None:
            args.figures_scratch_dir.mkdir(parents=True, exist_ok=True)
            build_static_figures(args.figures_scratch_dir)
            build_morl_figures(args.figures_scratch_dir)
        else:
            with tempfile.TemporaryDirectory() as scratch:
                build_static_figures(scratch)
                build_morl_figures(scratch)

    if not args.skip_serve:
        assemble_and_serve()


if __name__ == "__main__":
    main()
